"""
Author: No1lz
Description:
The script is mainly for records which is generated by Metasploit Module post/windows/gather/cachedump.
I want to change the record into the type that can be fed to Hashcat.
"""
import os

BASEDIR = "~/.msf4/loot/"
MSCacheFileList = []
HashcatMSCache = []

def FileHandling():
	os.system("ls " + BASEDIR + " > mscache.list")
	with open("mscache.list", "r") as f:
		for line in f.readlines():
			if "mscache" in line:
				MSCacheFileList.append(line.split("\n")[0])
	os.system("rm mscache.list")

def RecordHandling(index):
	TargetFile = MSCacheFileList[index]
	os.system("cp " + BASEDIR + TargetFile + " .")
	with open(TargetFile, "r") as f:
		flag = 0
		for line in f.readlines():
			mscache = "$DCC2"
			if flag == 0:
				flag = 1
				continue
			mscacheItem = line.split("\",\"")
			userName = mscacheItem[0][1:]
			cacheHash = mscacheItem[1]
			hashIteration = mscacheItem[2]
			mscache += "$" + hashIteration + "#" + userName + "#" + cacheHash
			print(mscache)
			HashcatMSCache.append(mscache)
	os.system("rm " + TargetFile)

def Menu():
	print("Which record do you want to dealing with?")
	index = 0
	for item in MSCacheFileList:
		recordTime = item.split("_")[0]
		print("[" + str(index) + "] " + recordTime[0:4] + "/" + recordTime[4:6] + "/" + recordTime[6:8] + " " + recordTime[8:10] + ":" + recordTime[10:12])
		index += 1
	choice = int(input("\n> "))
	while choice >= len(MSCacheFileList):
		print("Out Of Range.")
		choice = int(input("\n> "))
	return choice

if __name__ == "__main__":
	FileHandling()
	choice = Menu()
	RecordHandling(choice)

